### ISSUE TITLE
纯子别名出错

### ISSUE THREAD

**Issue by feilongproject** [lgc2333/bawiki-data#7]
https://[raw.gh.schale.top/lgc2333/bawiki-data/main/data/stu_alias.json](https://raw.gh.schale.top/lgc2333/bawiki-data/main/data/stu_alias.json)
纯子的别名不应该是琴里

**Comment by lgc2333** [comment]
pr welcome

**Comment by feilongproject** [comment]
#8 已pr，等待合并
